version: '3'

services:

  service_frontend:
    container_name: frontend
    image: artem12345png/hakaton:frontend
    command: ["streamlit", "run", "sl.py", "--server.enableCORS=false", "--server.enableXsrfProtection=false"]
    env_file:
      - sample.env
    ports:
      - "80:8501"



networks:
  default: